import { exportAction, folders, folderMenu } from './ui-helpers';
import {test,expect,type Page} from '@playwright/test';
import {PDFDocument} from 'pdf-lib';
import fs from 'node:fs/promises';
import {unpack} from '../src/core/archive';
import {createBlank} from '../src/core/blank';
async function folder(page:Page,name:string){await page.getByRole('button',{name:'新增資料夾',exact:true}).click();await page.getByLabel('資料夾名稱',{exact:true}).fill(name);await page.getByRole('button',{name:'儲存資料夾',exact:true}).click();await expect(page.locator('#search-scope')).toContainText(name);}
async function blank(page:Page,name:string,direction='直式'){await page.getByRole('button',{name:'新建空白文件',exact:true}).click();await page.getByLabel('空白文件名稱').fill(name);await page.getByRole('radio',{name:direction,exact:true}).check();await page.getByRole('button',{name:'建立文件',exact:true}).click();await expect(page.getByLabel('註記畫布',{exact:true})).toBeVisible();await expect(page.locator('.page-loading')).toHaveCount(0);}
async function noteDownload(page:Page){const result=page.waitForEvent('download');await exportAction(page,'工作存檔');return Buffer.from(await fs.readFile((await (await result).path())!));}
async function move(page:Page,name:string,target:string){await page.getByLabel('管理 '+name,{exact:true}).click();await page.getByRole('button',{name:'移動到資料夾',exact:true}).click();await page.getByLabel('目的資料夾').selectOption({label:target});await page.getByRole('button',{name:'確認移動',exact:true}).click();await expect(page.getByRole('button',{name:'確認移動',exact:true})).toHaveCount(0);}
test('folders, blank directions, imports and offline persistence preserve document identity',async({page,context})=>{
  await page.goto('/');await folder(page,'研讀');await page.getByRole('button',{name:'新建空白文件',exact:true}).click();await page.getByRole('button',{name:'取消',exact:true}).click();await expect(page.locator('.document-card')).toHaveCount(0);
  await blank(page,'直式筆記');const original=await noteDownload(page);const doc=await unpack(original);const source=await PDFDocument.load(doc.assets[doc.pdfHash].bytes);expect(source.getPage(0).getWidth()).toBeCloseTo(595.28);expect(source.getPage(0).getHeight()).toBeCloseTo(841.89);
  const emptyExport=page.waitForEvent('download');await exportAction(page,'匯出 PDF');expect((await PDFDocument.load(await fs.readFile((await (await emptyExport).path())!))).getPageCount()).toBe(1);
  await page.getByRole('button',{name:'返回文件庫'}).click();await expect(page.locator('.document-card')).toHaveCount(1);await page.getByLabel('管理 直式筆記',{exact:true}).click();await expect(page.getByRole('button',{name:'匯出初始空白 PDF',exact:true})).toBeVisible();await page.getByLabel('管理 直式筆記',{exact:true}).click();
  await folderMenu(page,'研讀');await page.getByLabel('刪除資料夾 研讀',{exact:true}).click();await page.getByRole('button',{name:'確認刪除資料夾',exact:true}).click();await expect(page.getByRole('alert')).toContainText('不是空的');await page.getByRole('button',{name:'取消',exact:true}).click();await page.getByLabel('關閉錯誤').click();
  await folderMenu(page,'研讀');await page.getByLabel('重新命名資料夾 研讀',{exact:true}).click();await page.getByLabel('資料夾名稱',{exact:true}).fill('學習');await page.getByRole('button',{name:'儲存資料夾',exact:true}).click();await expect(page.locator('.document-card')).toHaveCount(1);
  await folder(page,'工作');await blank(page,'橫式筆記','橫式');const landscape=await unpack(await noteDownload(page));const landPdf=await PDFDocument.load(landscape.assets[landscape.pdfHash].bytes);expect(landPdf.getPage(0).getWidth()).toBeCloseTo(841.89);expect(landPdf.getPage(0).getRotation().angle).toBe(0);expect(landscape.id).not.toBe(doc.id);
  await page.getByRole('button',{name:'文字',exact:true}).click();const box=(await page.getByLabel('註記畫布',{exact:true}).boundingBox())!;await page.mouse.click(box.x+90,box.y+150);await page.getByLabel('原位文字內容',{exact:true}).fill('空白頁上的想法');await page.getByLabel('原位文字內容',{exact:true}).press('Control+Enter');await expect(page.locator('.annotation-layer text')).toContainText('空白頁上的想法');
  const annotated=await noteDownload(page);await page.getByRole('button',{name:'返回文件庫'}).click();await move(page,'橫式筆記','學習');await expect(page.locator('.document-card')).toHaveCount(0);
  // Existing-document merge must not move the document to the current folder.
  await page.locator('input[type=file]').first().setInputFiles({name:'copy.pdfnote',mimeType:'application/octet-stream',buffer:annotated});await page.getByRole('button',{name:'合併',exact:true}).click();await expect(page.locator('.annotation-layer text')).toContainText('空白頁上的想法');const merged=await unpack(await noteDownload(page));expect(merged.id).toBe(landscape.id);expect(merged.pdfHash).toBe(landscape.pdfHash);await page.getByRole('button',{name:'返回文件庫'}).click();await expect(page.locator('.document-card')).toHaveCount(0);
  await page.locator('input[type=file]').first().setInputFiles({name:'copy.pdfnote',mimeType:'application/octet-stream',buffer:annotated});await page.getByRole('button',{name:'建立副本',exact:true}).click();const copy=await unpack(await noteDownload(page));expect(copy.id).not.toBe(landscape.id);await page.getByRole('button',{name:'返回文件庫'}).click();await expect(page.locator('.document-card')).toHaveCount(1);
  await folders(page);await page.getByRole('button',{name:'開啟資料夾 學習',exact:true}).click();await expect(page.locator('.document-card')).toHaveCount(2);await move(page,'直式筆記','未分類');await folders(page);await page.getByRole('button',{name:'未分類',exact:true}).click();await expect(page.getByRole('button',{name:'開啟 直式筆記',exact:true})).toBeVisible();
  await folders(page);await page.getByRole('button',{name:'全部文件',exact:true}).click();await page.screenshot({path:'test-results/v002-folders-desktop.png',fullPage:true});await page.setViewportSize({width:412,height:915});await page.screenshot({path:'test-results/v002-folders-mobile.png',fullPage:true});
  await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await context.setOffline(true);await page.reload();await expect(page.locator('.document-card')).toHaveCount(3);await folders(page);await page.getByRole('button',{name:'開啟資料夾 學習',exact:true}).click();await expect(page.locator('.document-card')).toHaveCount(1);await context.setOffline(false);
});
test('v2 database upgrades without clearing old documents or assets; old archives stay readable',async({page})=>{
  const seed=await createBlank('舊文件','portrait','old');delete seed.origin;
  await page.route('http://127.0.0.1:4173/',route=>route.fulfill({contentType:'text/html',body:'<html><body>Migration fixture</body></html>'}),{times:1});await page.goto('/');
  const serialized={...seed,assets:Object.fromEntries(Object.entries(seed.assets).map(([id,a])=>[id,{...a,bytes:Array.from(a.bytes)}]))};
  await page.evaluate(async seed=>{await new Promise<void>((resolve,reject)=>{const request=indexedDB.open('pdfnote-v1',2);request.onupgradeneeded=()=>{const db=request.result;db.createObjectStore('documents',{keyPath:'id'});db.createObjectStore('settings');db.createObjectStore('assets');};request.onerror=()=>reject(request.error);request.onsuccess=()=>{const db=request.result,tx=db.transaction(['documents','assets','settings'],'readwrite');for(const asset of Object.values(seed.assets))tx.objectStore('assets').put({...asset,bytes:new Uint8Array(asset.bytes)},asset.hash);tx.objectStore('documents').put({...seed,assets:Object.fromEntries(Object.entries(seed.assets).map(([id,a])=>[id,{hash:a.hash,mime:a.mime}]))});tx.objectStore('settings').put('keep-me','migration-test');tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>reject(tx.error);};});},serialized);
  await page.reload();await folders(page);await page.getByRole('button',{name:'未分類',exact:true}).click();await page.getByRole('button',{name:'開啟 舊文件',exact:true}).click();const restored=await unpack(await noteDownload(page));expect(restored.id).toBe(seed.id);expect(restored.assets[seed.pdfHash].bytes).toEqual(seed.assets[seed.pdfHash].bytes);
  const result=await page.evaluate(()=>new Promise<{version:number;setting:string}>(resolve=>{const request=indexedDB.open('pdfnote-v1');request.onsuccess=()=>{const db=request.result,tx=db.transaction('settings');const read=tx.objectStore('settings').get('migration-test');read.onsuccess=()=>{resolve({version:db.version,setting:read.result});db.close();};};}));expect(result).toEqual({version:4,setting:'keep-me'});
});
test('failed blank creation is atomic and repeated clicks produce one document',async({page})=>{
  await page.goto('/');await expect(page.getByRole('button',{name:'新建空白文件',exact:true})).toBeVisible();
  await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:Parameters<IDBObjectStore['put']>){if(this.name==='documents')throw new DOMException('Simulated disk full','QuotaExceededError');return original.apply(this,args);};});
  await page.getByRole('button',{name:'新建空白文件',exact:true}).click();await page.getByRole('button',{name:'建立文件',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Simulated disk full');await page.getByRole('button',{name:'取消',exact:true}).click();await expect(page.locator('.document-card')).toHaveCount(0);await page.reload();
  await page.getByRole('button',{name:'新建空白文件',exact:true}).click();await page.getByRole('button',{name:'建立文件',exact:true}).evaluate((button:HTMLButtonElement)=>{button.click();button.click();});await expect(page.getByLabel('註記畫布',{exact:true})).toBeVisible();await page.getByRole('button',{name:'返回文件庫'}).click();await expect(page.locator('.document-card')).toHaveCount(1);
});
