import { exportAction, pageSettings, folders, folderMenu } from './ui-helpers';
import {test,expect,type Page} from '@playwright/test';
import {PDFDocument,degrees} from 'pdf-lib';
import fs from 'node:fs/promises';
import sharp from 'sharp';
import {createBlank} from '../src/core/blank';
import {addAsset,edit,heads,merge,type Annotation,type NoteDocument} from '../src/core/model';
import {pack,unpack} from '../src/core/archive';
const pen=(x:number,y:number):Annotation=>({kind:'pen',page:1,x,y,width:1,height:80,color:'#123456',weight:2,opacity:1,points:[{x:0,y:0},{x:0,y:80}]});
async function open(page:Page,doc:NoteDocument){await page.goto('/');await page.locator('input[type=file]').first().setInputFiles({name:'test.pdfnote',mimeType:'application/octet-stream',buffer:Buffer.from(pack(doc))});await expect(page.getByLabel('註記畫布',{exact:true})).toBeVisible();await expect(page.locator('.page-loading')).toHaveCount(0);}
async function download(page:Page){const promise=page.waitForEvent('download');await exportAction(page,'工作存檔');return unpack(await fs.readFile((await (await promise).path())!));}
async function at(page:Page,x:number,y:number,n=1){return page.locator(`[data-page="${n}"] .annotation-layer > g`).evaluate((g,p)=>{const q=new DOMPoint(p.x,p.y).matrixTransform((g as SVGGraphicsElement).getScreenCTM()!);return {x:q.x,y:q.y};},{x,y});}
async function sweep(page:Page,a:{x:number;y:number},b:{x:number;y:number}){await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y);await page.mouse.up();}
test('swept eraser excludes text, groups undo and redo, cancels, protects newer heads',async({page})=>{
  let doc=await createBlank('擦除驗收','portrait','A');for(const [id,x] of [['a',100],['b',180],['c',180]] as const)doc=edit(doc,id,pen(x,100),'A');
  doc=edit(doc,'text',{...pen(140,100),kind:'text',width:150,height:100,text:'保留文字',fontSize:18},'A');await open(page,doc);
  await page.getByRole('button',{name:'橡皮擦',exact:true}).click();await page.getByLabel('橡皮擦直徑').fill('16');await page.getByLabel('橡皮擦直徑').press('Enter');
  const a=await at(page,70,140),b=await at(page,230,140);await page.mouse.move(a.x,a.y);await expect(page.locator('.eraser-cursor')).toHaveAttribute('r','8');await expect(page.locator('[data-object]')).toHaveCount(4);
  await page.mouse.down();await page.mouse.move(b.x,b.y);await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await page.mouse.up();await expect(page.locator('[data-object]')).toHaveCount(4);
  await sweep(page,a,b);await expect(page.locator('[data-object]')).toHaveCount(1);const erased=await download(page);for(const id of ['a','b','c'])expect(heads(erased,id)[0].value).toBeNull();
  await page.getByRole('button',{name:'復原',exact:true}).click();await expect(page.locator('[data-object]')).toHaveCount(4);await page.getByRole('button',{name:'重做',exact:true}).click();await expect(page.locator('[data-object]')).toHaveCount(1);
  // Simulates a concurrent durable update delivered via another tab, while this editor keeps its history.
  const latest=await download(page),remote=edit(latest,'a',pen(100,100),'remote');
  await page.evaluate(async op=>{await new Promise<void>((resolve,reject)=>{const req=indexedDB.open('pdfnote-v1');req.onsuccess=()=>{const db=req.result,tx=db.transaction('documents','readwrite'),store=tx.objectStore('documents'),get=store.get(op.docId);get.onsuccess=()=>store.put({...get.result,operations:[...get.result.operations,op.operation]});tx.oncomplete=()=>{db.close();const channel=new BroadcastChannel('pdfnote');channel.postMessage('saved');channel.close();resolve();};tx.onerror=()=>reject(tx.error);};});},{docId:doc.id,operation:remote.operations.at(-1)!});
  await expect(page.locator('[data-object]')).toHaveCount(2);await page.getByRole('button',{name:'復原',exact:true}).click();await expect(page.getByRole('alert')).toContainText('其他修改');await expect(page.locator('[data-object]')).toHaveCount(2);
});
test('eraser uses page matrix with crop, rotation, zoom and DPR 2; tool sizes remain independent',async({browser})=>{
  const context=await browser.newContext({deviceScaleFactor:2,viewport:{width:1440,height:980}}),page=await context.newPage();
  let doc=await createBlank('座標','portrait','A');const pdf=await PDFDocument.create(),p=pdf.addPage([600,800]);p.setCropBox(25,35,530,710);p.setRotation(degrees(90));const asset=await addAsset(await pdf.save(),'application/pdf');doc={...doc,pdfHash:asset.hash,originalHash:asset.hash,assets:{[asset.hash]:asset}};doc=edit(doc,'a',pen(100,100),'A');await open(page,doc);
  await pageSettings(page);await page.getByRole('button',{name:'縮小',exact:true}).click();await expect(page.locator('.page-loading')).toHaveCount(0);await page.getByRole('button',{name:'橡皮擦',exact:true}).click();await page.getByLabel('橡皮擦直徑').fill('40');await page.getByLabel('橡皮擦直徑').press('Enter');const a=await at(page,80,140),b=await at(page,120,140);await sweep(page,a,b);await expect(page.locator('[data-object]')).toHaveCount(0);await page.getByRole('button',{name:'復原',exact:true}).click();await expect(page.locator('[data-object]')).toHaveCount(1);
  await page.getByRole('button',{name:'畫筆',exact:true}).click();await expect(page.getByLabel('註記畫布',{exact:true})).toHaveCSS('cursor','crosshair');await page.getByLabel('直徑',{exact:true}).fill('8');await page.getByLabel('直徑',{exact:true}).press('Enter');await page.getByRole('button',{name:'螢光筆',exact:true}).click();await expect(page.getByLabel('註記畫布',{exact:true})).toHaveCSS('cursor','crosshair');await expect(page.getByLabel('橡皮擦直徑')).toHaveCount(0);await page.getByRole('button',{name:'橡皮擦',exact:true}).click();await expect(page.getByLabel('橡皮擦直徑')).toHaveValue('40');await page.reload();await page.getByRole('button',{name:'開啟 座標',exact:true}).click();await page.getByRole('button',{name:'橡皮擦',exact:true}).click();await expect(page.getByLabel('橡皮擦直徑')).toHaveValue('40');await page.getByRole('button',{name:'畫筆',exact:true}).click();await expect(page.getByLabel('直徑',{exact:true})).toHaveValue('8');await context.close();
});
test('vertical and horizontal arbitrary-angle text matches PDF export and archive',async({page})=>{
  await page.setViewportSize({width:1440,height:1200});let doc=await createBlank('文字排版','portrait','A');for(const [i,angle] of [0,45,90,37.25].entries())for(const [j,writingMode] of (['horizontal-tb','vertical-rl'] as const).entries())doc=edit(doc,`t${i}${j}`,{kind:'text',page:1,x:45+j*270,y:40+i*180,width:170,height:130,color:'#123456',opacity:1,weight:1,fontSize:18,text:'中文 Ab12，。\n換欄第二行',writingMode,angle},'A');
  await open(page,doc);await page.getByLabel('關閉提示').click();const before=await page.locator('.paper').screenshot({path:'test-results/v003-text-before.png'});expect((await download(page)).operations).toEqual(doc.operations);
  const dl=page.waitForEvent('download');await exportAction(page,'匯出 PDF');const result=await fs.readFile((await (await dl).path())!);await page.getByRole('button',{name:'返回文件庫'}).click();await page.locator('input[type=file]').first().setInputFiles({name:'flat.pdf',mimeType:'application/pdf',buffer:result});await expect(page.getByLabel('註記畫布',{exact:true})).toBeVisible();await expect(page.locator('.page-loading')).toHaveCount(0);await page.getByLabel('關閉提示').click();const after=await page.locator('.paper').screenshot({path:'test-results/v003-text-after.png'});
  const aa=await sharp(before).removeAlpha().raw().toBuffer({resolveWithObject:true}),bb=await sharp(after).removeAlpha().raw().toBuffer({resolveWithObject:true});expect(aa.info).toEqual(bb.info);let sum=0;for(let i=0;i<aa.data.length;i++)sum+=Math.abs(aa.data[i]-bb.data[i]);expect(sum/aa.data.length).toBeLessThan(2);
});
test('continuous mixed pages virtualize, navigate, switch axes and restore local anchor',async({page})=>{
  const pdf=await PDFDocument.create();for(let n=0;n<30;n++){const p=pdf.addPage([500+(n%3)*40,680+(n%4)*30]);if(n%2)p.setRotation(degrees(90));}
  const asset=await addAsset(await pdf.save(),'application/pdf');let doc=await createBlank('連續閱讀','portrait','A');doc={...doc,pdfHash:asset.hash,originalHash:asset.hash,assets:{[asset.hash]:asset},pageCount:30};await open(page,doc);
  await expect(page.locator('.paper')).toHaveCount(30);expect(await page.locator('.paper canvas').count()).toBeLessThan(8);const scroll=page.locator('.page-scroll');await scroll.hover();await page.mouse.wheel(0,850);await expect(page.getByLabel('頁碼',{exact:true})).not.toHaveValue('1');
  await page.getByLabel('頁碼',{exact:true}).fill('20');await page.getByLabel('頁碼',{exact:true}).press('Enter');await expect(page.getByLabel('頁碼',{exact:true})).toHaveValue('20');await expect(page.locator('[data-page="20"] canvas')).toBeVisible();const height=await page.locator('[data-page="20"]').evaluate(n=>n.clientHeight);
  await pageSettings(page);await page.getByLabel('展示方向').selectOption('horizontal');await expect(page.locator('[data-page="20"]')).toHaveCSS('height',height+'px');await expect(page.getByLabel('頁碼',{exact:true})).toHaveValue('20');const start=await scroll.evaluate(n=>n.scrollLeft);await scroll.hover();await page.mouse.wheel(0,350);await expect.poll(()=>scroll.evaluate(n=>n.scrollLeft)).toBeGreaterThan(start);
  const prevented=await scroll.evaluate(n=>!n.dispatchEvent(new WheelEvent('wheel',{ctrlKey:true,deltaY:10,cancelable:true,bubbles:true})));expect(prevented).toBe(false);
  const position=await page.getByLabel('頁碼',{exact:true}).inputValue();await page.getByRole('button',{name:'返回文件庫'}).click();await page.getByRole('button',{name:'開啟 連續閱讀',exact:true}).click();await pageSettings(page);await expect(page.getByLabel('展示方向')).toHaveValue('horizontal');await expect(page.getByLabel('頁碼',{exact:true})).toHaveValue(position);expect(await page.locator('.paper canvas').count()).toBeLessThan(8);await page.screenshot({path:'test-results/v003-continuous.png'});
});
test('mouse drags preserve IDs, reject descendant drops, and mobile folder move can return to root',async({page})=>{
  await page.goto('/');const folder=async(name:string)=>{await folders(page);await page.getByRole('button',{name:'全部文件',exact:true}).click();await page.getByRole('button',{name:'新增資料夾',exact:true}).click();await page.getByLabel('資料夾名稱',{exact:true}).fill(name);await page.getByRole('button',{name:'儲存資料夾',exact:true}).click();await folders(page);await expect(page.getByRole('button',{name:'開啟資料夾 '+name,exact:true})).toBeVisible();};
  await folder('A');await folder('B');const tile=(name:string)=>page.locator('.folder-tile').filter({has:page.getByRole('button',{name:'開啟資料夾 '+name,exact:true})});const aId=await tile('A').getAttribute('data-folder-id');
  await tile('A').dragTo(tile('B'));await expect(tile('A')).toHaveCSS('margin-left','20px');await tile('B').dragTo(tile('A'));await expect(tile('B')).toHaveCSS('margin-left','0px');await expect(tile('A')).toHaveAttribute('data-folder-id',aId!);
  await folderMenu(page,'A');await page.getByLabel('移動資料夾 A',{exact:true}).click();await page.getByLabel('目的資料夾').selectOption('');await page.getByRole('button',{name:'確認移動',exact:true}).click();await expect(tile('A')).toHaveCSS('margin-left','0px');
  await folders(page);await page.getByRole('button',{name:'全部文件',exact:true}).click();const doc=await createBlank('拖曳文件','portrait','A');await page.locator('input[type=file]').first().setInputFiles({name:'drag.pdfnote',mimeType:'application/octet-stream',buffer:Buffer.from(pack(doc))});await expect(page.getByLabel('註記畫布',{exact:true})).toBeVisible();await page.getByRole('button',{name:'返回文件庫'}).click();
  await page.locator('.document-card').dragTo(tile('A'));await expect(page.locator('.card-bottom')).toContainText('A');await page.locator('.document-card').dragTo(page.locator('[data-drop-target="unfiled"]'));await expect(page.locator('.card-bottom')).toContainText('未分類');await page.getByRole('button',{name:'開啟 拖曳文件',exact:true}).click();expect((await download(page)).id).toBe(doc.id);
});

test('one eraser gesture crosses pages, skips conflicts, and a failed save is atomic',async({page})=>{
  const pdf=await PDFDocument.create();pdf.addPage([400,260]);pdf.addPage([400,260]);const asset=await addAsset(await pdf.save(),'application/pdf');
  let doc=await createBlank('跨頁擦除','portrait','A');doc={...doc,pdfHash:asset.hash,originalHash:asset.hash,assets:{[asset.hash]:asset},pageCount:2};doc=edit(doc,'one',pen(100,70),'A');doc=edit(doc,'two',{...pen(100,70),page:2},'A');doc=edit(doc,'conflict',pen(100,170),'A');doc=merge(edit(doc,'conflict',{...pen(100,170),color:'#ff0000'},'A'),edit(doc,'conflict',{...pen(100,170),color:'#0000ff'},'B'));
  await open(page,doc);await page.getByLabel('關閉提示').click();await page.getByRole('button',{name:'橡皮擦',exact:true}).click();await sweep(page,await at(page,100,60,1),await at(page,100,160,2));await expect(page.locator('[data-object]')).toHaveCount(0);await expect(page.locator('.search-status')).toContainText('衝突筆跡');const result=await download(page);expect(heads(result,'one')[0].value).toBeNull();expect(heads(result,'two')[0].value).toBeNull();expect(heads(result,'conflict')).toHaveLength(2);
  await page.getByRole('button',{name:'復原',exact:true}).click();await expect(page.locator('[data-object]')).toHaveCount(2);
  await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:Parameters<IDBObjectStore['put']>){if(this.name==='documents')throw new DOMException('Batch disk full','QuotaExceededError');return original.apply(this,args);};});
  await sweep(page,await at(page,100,60,1),await at(page,100,160,2));await expect(page.getByRole('alertdialog')).toBeVisible();await expect(page.locator('[data-object]')).toHaveCount(2);
  const stored=await page.evaluate(id=>new Promise<any>(resolve=>{const request=indexedDB.open('pdfnote-v1');request.onsuccess=()=>{const db=request.result,read=db.transaction('documents').objectStore('documents').get(id);read.onsuccess=()=>{resolve(read.result);db.close();};};}),doc.id);expect(heads(stored,'one')[0].value).not.toBeNull();expect(heads(stored,'two')[0].value).not.toBeNull();
});

test('text property editing, rotated selection, resizing and rotation handle persist',async({page})=>{
  let doc=await createBlank('文字互動','portrait','A');doc=edit(doc,'text',{...pen(150,180),kind:'text',width:180,height:100,text:'中文 Ab12\n換欄',fontSize:18},'A');await open(page,doc);await page.getByLabel('關閉提示').click();await page.getByRole('button',{name:'選取',exact:true}).click();const center=await at(page,240,230);await sweep(page,await at(page,140,170),center);
  await page.getByLabel('文字方向',{exact:true}).selectOption('vertical-rl');await page.getByLabel('寬度',{exact:true}).fill('200');await page.getByRole('button',{name:'套用變更',exact:true}).click();await page.getByLabel('物件旋轉角度').fill('45');await page.getByLabel('物件旋轉角度').press('Enter');await expect(page.locator('[data-object="text"] > g').first()).toHaveAttribute('transform',/^matrix\(0\.707/);
  let result=await download(page);expect(heads(result,'text')[0].value).toMatchObject({writingMode:'vertical-rl',angle:45,width:200});
  const handle=page.getByLabel('旋轉所選物件'),box=(await handle.boundingBox())!;const centerNow=(heads(result,'text')[0].value as Annotation);const target=await at(page,centerNow.x+centerNow.width/2+100,centerNow.y+centerNow.height/2);await sweep(page,{x:box.x+box.width/2,y:box.y+box.height/2},target);await expect(page.getByLabel('物件旋轉角度')).toHaveValue('90');
  await page.getByRole('button',{name:'水平 0°',exact:true}).click();result=await download(page);expect(heads(result,'text')[0].value).toMatchObject({angle:0,writingMode:'vertical-rl'});await page.reload();await page.getByRole('button',{name:'開啟 文字互動',exact:true}).click();await expect(page.locator('[data-object="text"] > g').first()).toHaveAttribute('transform','matrix(1 0 0 1 150 180)');
});

test('v3 database and legacy page-scroll settings migrate on the same origin without rewriting old operations',async({page})=>{
  let doc=await createBlank('v002 舊資料','portrait','old');const pdf=await PDFDocument.create();for(let i=0;i<3;i++)pdf.addPage([500,800]);const asset=await addAsset(await pdf.save(),'application/pdf');doc={...doc,pdfHash:asset.hash,originalHash:asset.hash,assets:{[asset.hash]:asset},pageCount:3};
  await page.route('http://127.0.0.1:4173/',route=>route.fulfill({contentType:'text/html',body:'<html>v3 migration fixture</html>'}),{times:1});await page.goto('/');
  await page.evaluate(async seed=>{await new Promise<void>((resolve,reject)=>{const r=indexedDB.open('pdfnote-v1',3);r.onupgradeneeded=()=>{const db=r.result;db.createObjectStore('documents',{keyPath:'id'});for(const name of ['assets','settings','library'])db.createObjectStore(name);};r.onsuccess=()=>{const db=r.result,tx=db.transaction(['documents','assets','settings','library'],'readwrite');tx.objectStore('documents').put(seed.doc);tx.objectStore('assets').put({...seed.asset,bytes:new Uint8Array(seed.asset.bytes)},seed.asset.hash);tx.objectStore('settings').put({page:2,zoom:1.5,rotation:90,scroll:120},'position:'+seed.doc.id);tx.objectStore('library').put({format:1,kind:'library',operations:[{id:'f1',entity:'folder:old-folder',value:{name:'舊分類'},device:'old',time:'2026-01-01',parents:[]},{id:'m1',entity:'member:'+seed.doc.id,value:{folderId:'old-folder'},device:'old',time:'2026-01-01',parents:[]}]},'main');tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>reject(tx.error);};});},{doc:{...doc,assets:{[asset.hash]:{hash:asset.hash,mime:asset.mime}}},asset:{...asset,bytes:Array.from(asset.bytes)}});
  await page.reload();await expect(page.locator('.folder-tile')).toHaveCSS('margin-left','0px');await folders(page);await page.getByRole('button',{name:'開啟資料夾 舊分類',exact:true}).click();await page.getByRole('button',{name:'開啟 v002 舊資料',exact:true}).click();await expect(page.getByLabel('頁碼',{exact:true})).toHaveValue('2');await pageSettings(page);await expect(page.getByLabel('展示方向')).toHaveValue('vertical');await expect(page.locator('[data-page="2"]')).toHaveCSS('height','750px');
  const restored=await download(page);expect(restored.operations).toEqual(doc.operations);expect(restored.pdfHash).toBe(doc.pdfHash);expect(restored.format).toBe(1);
  const pos=await page.evaluate(id=>new Promise<any>(resolve=>{const r=indexedDB.open('pdfnote-v1');r.onsuccess=()=>{const db=r.result,read=db.transaction('settings').objectStore('settings').get('position:'+id);read.onsuccess=()=>{resolve(read.result);db.close();};};}),doc.id);expect(pos.page).toBe(2);expect(pos.anchor.y).toBeCloseTo(96/750,2);
});
