import { exportAction, pageSettings } from './ui-helpers';
import { test,expect } from '@playwright/test';
import { PDFDocument,StandardFonts,rgb,degrees } from 'pdf-lib';
import fs from 'node:fs/promises';
import { unzipSync,strFromU8 } from 'fflate';
test('real PDF editing, persistence, both exports, duplicate import and offline restart',async({page,context})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  const pdf=await PDFDocument.create();const font=await pdf.embedFont(StandardFonts.Helvetica);
  const p=pdf.addPage([595,842]);p.drawText('PDFnote acceptance test',{x:60,y:740,size:24,font,color:rgb(.1,.25,.2)});p.drawText('Select this text. Search this text.',{x:60,y:680,size:15,font});
  const second=pdf.addPage([600,800]);second.setCropBox(25,35,530,710);second.setRotation(degrees(90));second.drawText('Rotated crop page',{x:70,y:650,size:22,font});
  const bytes=Buffer.from(await pdf.save());
  await page.goto('/');await expect(page.getByRole('heading',{name:'我的文件'})).toBeVisible();
  await page.screenshot({path:'test-results/library-empty.png',fullPage:true});
  await page.locator('input[type=file]').first().setInputFiles({name:'acceptance.pdf',mimeType:'application/pdf',buffer:bytes});
  await expect(page.getByLabel('註記畫布',{exact:true})).toBeVisible();await expect(page.locator('.page-loading')).toHaveCount(0);
  await expect(page.locator('[data-page="1"] .textLayer')).toContainText('PDFnote acceptance test');
  await page.getByRole('button',{name:'文字',exact:true}).click();const canvas=page.getByLabel('註記畫布',{exact:true});const box=(await canvas.boundingBox())!;
  await page.mouse.click(box.x+80,box.y+210);await page.getByLabel('原位文字內容',{exact:true}).fill('繁體中文筆記\n離線也能工作');await page.getByLabel('原位文字內容',{exact:true}).press('Control+Enter');
  await expect(page.locator('.annotation-layer text')).toContainText('繁體中文筆記');
  await page.getByRole('button',{name:'畫筆',exact:true}).click();await page.mouse.move(box.x+70,box.y+300);await page.mouse.down();await page.mouse.move(box.x+200,box.y+330,{steps:14});await page.mouse.up();
  await page.getByRole('button',{name:'螢光筆',exact:true}).click();await page.mouse.move(box.x+60,box.y+150);await page.mouse.down();await page.mouse.move(box.x+290,box.y+150,{steps:15});await page.mouse.up();
  // A real tiny PNG, used as an independent image object.
  const sharp=(await import('sharp')).default;const image=await sharp({create:{width:120,height:80,channels:4,background:'#bd704d'}}).png().toBuffer();
  await page.getByRole('button',{name:'插入圖片',exact:true}).click();await page.locator('.editor input[type=file]').setInputFiles({name:'image.png',mimeType:'image/png',buffer:image});
  await page.locator('.gallery-thumb').first().click();await page.mouse.click(box.x+30,box.y+30);await expect(page.locator('.annotation-layer image')).toBeVisible();await expect(page.locator('.reader-footer')).toContainText('4 個物件');
  await page.getByRole('button',{name:'屬性',exact:true}).click();await page.getByLabel('寬度',{exact:true}).fill('160');await page.getByRole('button',{name:'套用變更'}).click();await expect(page.locator('.annotation-layer image')).toHaveAttribute('width','160');
  await page.getByRole('button',{name:'復原',exact:true}).click();await expect(page.locator('.annotation-layer image')).toHaveAttribute('width','240');
  await page.getByRole('button',{name:'重做',exact:true}).click();await expect(page.locator('.annotation-layer image')).toHaveAttribute('width','160');
  await page.getByRole('button',{name:'閱讀',exact:true}).click();await page.screenshot({path:'test-results/editor-desktop.png',fullPage:true});
  const portablePromise=page.waitForEvent('download');await exportAction(page,'工作存檔');const portable=await portablePromise;const archive=await fs.readFile((await portable.path())!);await portable.saveAs('test-results/acceptance.pdfnote');
  const data=unzipSync(archive);const manifest=JSON.parse(strFromU8(data['manifest.json']));expect(Buffer.from(data['assets/'+manifest.originalHash])).toEqual(bytes);
  const pdfPromise=page.waitForEvent('download');await exportAction(page,'匯出 PDF');const exported=await pdfPromise;await exported.saveAs('test-results/acceptance-annotated.pdf');const merged=await PDFDocument.load(await fs.readFile((await exported.path())!));expect(merged.getPageCount()).toBe(2);
  await page.reload();await page.getByRole('button',{name:'開啟 acceptance',exact:true}).click();await expect(page.locator('.reader-footer')).toContainText('4 個物件');
  await page.getByLabel('頁碼',{exact:true}).fill('2');await page.getByLabel('頁碼',{exact:true}).press('Enter');await expect(page.locator('.page-loading')).toHaveCount(0);await pageSettings(page);await page.getByRole('button',{name:'旋轉頁面'}).click();await expect(page.locator('.page-loading')).toHaveCount(0);
  await page.getByRole('button',{name:'返回文件庫'}).click();await page.locator('input[type=file]').first().setInputFiles({name:'renamed.pdfnote',mimeType:'application/octet-stream',buffer:archive});await expect(page.getByRole('heading',{name:'這份文件已在你的文件庫'})).toBeVisible();await page.getByRole('button',{name:'取消',exact:true}).click();await expect(page.locator('.document-card')).toHaveCount(1);
  await page.locator('input[type=file]').first().setInputFiles({name:'renamed.pdfnote',mimeType:'application/octet-stream',buffer:archive});await page.getByRole('button',{name:'合併',exact:true}).click();await expect(page.locator('.reader-footer')).toContainText('第 2 頁');await page.getByLabel('頁碼',{exact:true}).fill('1');await page.getByLabel('頁碼',{exact:true}).press('Enter');await expect(page.locator('.reader-footer')).toContainText('4 個物件');
  await page.getByRole('button',{name:'返回文件庫'}).click();await page.locator('input[type=file]').first().setInputFiles({name:'same.pdfnote',mimeType:'application/octet-stream',buffer:archive});await page.getByRole('button',{name:'建立副本',exact:true}).click();await page.getByRole('button',{name:'返回文件庫'}).click();await expect(page.locator('.document-card')).toHaveCount(2);
  await page.screenshot({path:'test-results/library-documents.png',fullPage:true});
  await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await context.setOffline(true);await page.reload();await expect(page.locator('.document-card')).toHaveCount(2);await page.getByRole('button',{name:'開啟 acceptance',exact:true}).first().click();await page.getByLabel('頁碼',{exact:true}).fill('1');await page.getByLabel('頁碼',{exact:true}).press('Enter');await expect(page.locator('[data-page="1"] .textLayer')).toContainText('PDFnote acceptance test');await expect(page.locator('.reader-footer')).toContainText('4 個物件');
  const offlineDownload=page.waitForEvent('download');await exportAction(page,'匯出 PDF');await offlineDownload;
  await page.setViewportSize({width:412,height:915});await pageSettings(page);await page.getByRole('button',{name:'適合寬度',exact:true}).click();await page.screenshot({path:'test-results/editor-mobile.png',fullPage:true});await context.setOffline(false);
  expect(errors).toEqual([]);
});
