import { Button, EmptyState, StatusBadge } from './ui';
import { useState } from 'react';
import { Check, GitBranch, FileX2 } from 'lucide-react';
import { conflicts, nameOf, type NoteDocument, type Operation } from '../core/model';
import { Preview } from './Preview';
export function Conflicts({documents,onResolve,management,managementCount=0}:{documents:NoteDocument[];onResolve:(doc:NoteDocument,id:string,op:Operation)=>Promise<void>;management?:React.ReactNode;managementCount?:number}) {
  const items=documents.flatMap(doc=>conflicts(doc).map(c=>({...c,doc})));
  const [saving,setSaving]=useState(false),[error,setError]=useState('');
  const [selected,setSelected]=useState('');const [version,setVersion]=useState<string>();
  const current=items.find(c=>c.doc.id+':'+c.id===selected);const candidate=current?.versions.find(o=>o.id===version);
  const annotation=current?.versions.map(v=>v.value).find(v=>v&&v.kind!=='document');
  return <><header className="content-header"><div><h1>衝突管理</h1></div><span className="count-badge">{items.length+managementCount} 個待處理物件</span></header>
    {management}
    {!items.length?(managementCount?null:<div className="empty-state"><div className="empty-icon"><Check size={34}/></div><h2>目前沒有待處理的衝突</h2><p>兩台裝置同時修改同一物件時，<br/>你可以在這裡比較版本，再選擇保留哪一個。</p></div>):<div className={'conflict-layout '+(current?'has-detail':'')}><div className="conflict-list">{items.map(c=>{const value=c.versions.find(o=>o.value)?.value;return <button aria-pressed={current?.doc.id===c.doc.id&&current?.id===c.id} disabled={saving} key={c.doc.id+':'+c.id} className={current===c?'active':''} onClick={()=>{setSelected(c.doc.id+':'+c.id);setVersion(undefined);setError('');}}><GitBranch size={20}/><div><strong>{nameOf(c.doc)}</strong><small>{value&&value.kind!=='document'?'第 '+value.page+' 頁 · '+({pen:'筆跡',highlight:'螢光筆',text:'文字',image:'圖片'}[value.kind]):'文件資訊'} · {c.versions.length} 個版本</small></div></button>;})}</div><section className="conflict-detail">{current?<><Button className="conflict-back" disabled={saving} onClick={()=>{setSelected('');setVersion(undefined);}}>返回衝突清單</Button><h2>{nameOf(current.doc)}</h2><p>目前物件：{current.id.slice(0,8)} · {annotation&&annotation.kind!=='document'?`第 ${annotation.page} 頁`:'文件資訊'}</p><div className="version-tabs">{current.versions.map((v,i)=><button aria-pressed={v.id===version} disabled={saving} key={v.id} className={v.id===version?'active':''} onClick={()=>setVersion(v.id)}>版本 {i+1}{v.value===null?' · 已刪除':''}</button>)}</div>{candidate?<><div className="version-info">裝置 {candidate.device.slice(0,8)} · {new Date(candidate.time).toLocaleString('zh-TW')}</div><div className="candidate-preview">{candidate.value===null?<div className="empty-state compact"><FileX2 size={38}/><h3>已刪除</h3><p>選擇此版本後，這個物件將保持刪除狀態。</p></div>:candidate.value.kind==='document'?<h3>{candidate.value.name}</h3>:<Preview doc={current.doc} page={candidate.value.page} candidate={candidate}/>}</div><Button variant="primary" busy={saving} onClick={async()=>{setSaving(true);setError('');try{await onResolve(current.doc,current.id,candidate);setVersion(undefined);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setSaving(false);}}}><Check size={18}/>保留此版本</Button></>:<div className="choose-version">請選擇上方的版本以查看內容。</div>}</>:<div className="empty-state compact"><GitBranch size={32}/><p>選擇左側物件，開始比較版本。</p></div>}{error&&<p role="alert" className="field-error">{error}</p>}{saving&&<p role="status">正在保存選擇…</p>}</section></div>}
  </>;
}
