import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ChevronLeft, ChevronRight, RotateCw, Minus, Plus, MousePointer2, Hand, PenLine, Highlighter, Type, ImagePlus, Eraser, Undo2, Redo2, Download, Search, FileSliders } from 'lucide-react';
import { ActionMenu, Button, Dialog, IconButton, SlideRegion } from './ui';
import { NumberInput, SizeControl } from './NumericControl';
import { toolSettings } from '../core/ui-policy';
export type Tool='read'|'select'|'pen'|'highlight'|'text'|'erase'|'image'|'page';
export type SelectionMode='box'|'lasso';
export type ToolbarProps={landscape?:boolean;name:string;status:string;tool:Tool;onTool:(t:Tool)=>void;color:string;onColor:(s:string)=>void;weight:number;onWeight:(n:number)=>void;eraserSize:number;onEraser:(n:number)=>void;onBack:()=>void;onExport:(k:'pdf'|'note')=>void;onImage:()=>void;ready:boolean;working:boolean;canUndo:boolean;canRedo:boolean;onUndo:()=>void;onRedo:()=>void;selectionMode:SelectionMode;onSelectionMode:(m:SelectionMode)=>void;dirty:boolean;page:number;pages:number;onPage:(n:number)=>void;zoom:number;onZoom:(n:number)=>void;onFit:()=>void;onFitPage:()=>void;zoomMode:'manual'|'width'|'page';onRotate:()=>void;layout:'vertical'|'horizontal';onLayout:(l:'vertical'|'horizontal')=>void;query:string;onQuery:(s:string)=>void;onSearch:()=>void;onPrevious?:()=>void;searchSummary?:string};
export function EditorToolbar(p:ToolbarProps){
  const [exportOpen,setExportOpen]=useState(false),[searchOpen,setSearchOpen]=useState(false),[infoOpen,setInfoOpen]=useState(false);
  const search=useRef<HTMLInputElement>(null),searchToggle=useRef<HTMLButtonElement>(null),modesRef=useRef<HTMLDivElement>(null),navigation=useRef<HTMLDivElement>(null);
  const returnSearchFocus=()=>{(searchToggle.current||navigation.current?.querySelector<HTMLButtonElement>('[aria-label="文件與閱讀操作"]'))?.focus();};
  useEffect(()=>{const root=modesRef.current,active=root?.querySelector<HTMLElement>('[aria-pressed="true"]');if(root&&active){const r=root.getBoundingClientRect(),a=active.getBoundingClientRect();if(a.left<r.left)root.scrollLeft+=a.left-r.left;else if(a.right>r.right)root.scrollLeft+=a.right-r.right;}},[p.tool,p.landscape]);
  useEffect(()=>{if(searchOpen)search.current?.focus();},[searchOpen]);
  const modes:[Tool,typeof Hand,string][]=[['page',FileSliders,'頁面'],['read',Hand,'閱讀'],['select',MousePointer2,'選取'],['pen',PenLine,'畫筆'],['highlight',Highlighter,'螢光筆'],['text',Type,'文字'],['erase',Eraser,'橡皮擦']];
  return <div className="editor-controls">
    {p.landscape?<div ref={navigation} className="landscape-navigation"><IconButton label="返回文件庫" onClick={p.onBack}><ArrowLeft size={20}/></IconButton><ActionMenu label="文件與閱讀操作" caption={(p.tool==='image'?'圖片':modes.find(([id])=>id===p.tool)?.[2])+' · 更多'}><p className="menu-document-status" role="status">{p.status}</p><Button onClick={()=>setInfoOpen(true)}>文件資訊與頁碼 · {p.page} / {p.pages}</Button><Button onClick={()=>setSearchOpen(true)}>搜尋 PDF</Button><Button onClick={()=>setExportOpen(true)}>匯出文件</Button><Button disabled={!p.canUndo||p.working} onClick={p.onUndo}>復原</Button><Button disabled={!p.canRedo||p.working} onClick={p.onRedo}>重做</Button></ActionMenu>{/失敗|錯誤|未儲存/.test(p.status)&&<span className="save-error-indicator" role="alert" title={p.status}>儲存異常</span>}</div>:<header className="reader-header"><IconButton label="返回文件庫" onClick={p.onBack}><ArrowLeft size={20}/></IconButton><button className="reader-title" aria-label="查看完整文件名稱與狀態" onClick={()=>setInfoOpen(true)}><strong>{p.name}</strong><small role="status">{p.status}</small></button><div className="page-controls"><div className="page-navigation"><IconButton label="上一頁" disabled={!p.ready||p.page<=1} onClick={()=>p.onPage(p.page-1)}><ChevronLeft size={18}/></IconButton><label><span className="visually-hidden">頁碼</span><NumberInput label="頁碼" disabled={!p.ready} integer value={p.page} min={1} max={p.pages} onCommit={p.onPage}/> / {p.pages}</label><IconButton label="下一頁" disabled={!p.ready||p.page>=p.pages} onClick={()=>p.onPage(p.page+1)}><ChevronRight size={18}/></IconButton></div>

      <div className="page-secondary"><button ref={searchToggle} aria-label="搜尋 PDF" aria-expanded={searchOpen} aria-controls="pdf-search" onClick={()=>{if(searchOpen)p.onQuery('');setSearchOpen(v=>!v);}}><Search size={18}/><span>搜尋</span></button></div>
    </div><Button aria-label="匯出文件" onClick={()=>setExportOpen(true)}><Download size={18}/><span>匯出</span></Button></header>}
    <div className="tools"><div ref={modesRef} className="tool-group tool-modes" role="toolbar" aria-label="筆記工具（窄版可左右捲動）">{modes.map(([id,Icon,label])=><Button key={id} variant="quiet" className={p.tool===id?'active':''} onClick={()=>p.onTool(id)} aria-label={label} aria-pressed={p.tool===id}><Icon size={19}/><span>{label}</span></Button>)}<IconButton aria-pressed={p.tool==='image'} className={p.tool==='image'?'active':''} label="插入圖片" onClick={p.onImage} disabled={!p.ready}><ImagePlus size={19}/></IconButton></div><div className="tool-group history-tools"><IconButton label="復原" disabled={!p.canUndo||p.working} onClick={p.onUndo}><Undo2 size={19}/></IconButton><IconButton label="重做" disabled={!p.canRedo||p.working} onClick={p.onRedo}><Redo2 size={19}/></IconButton></div></div>
    <SlideRegion className="search-overlay" open={searchOpen} returnFocus={returnSearchFocus}><form id="pdf-search" className="pdf-search" onSubmit={e=>{e.preventDefault();p.onSearch();}} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();setSearchOpen(false);p.onQuery('');returnSearchFocus();}}}><input ref={search} aria-label="搜尋 PDF 文字" placeholder="搜尋文件文字" value={p.query} onChange={e=>p.onQuery(e.target.value)}/><span role="status">{p.searchSummary}</span><Button disabled={!p.query.trim()} onClick={p.onPrevious}>前一筆</Button><Button type="submit" disabled={!p.ready||!p.query.trim()}>下一筆</Button><Button onClick={()=>{setSearchOpen(false);p.onQuery('');returnSearchFocus();}}>關閉搜尋</Button></form></SlideRegion>
    {infoOpen&&<Dialog title="文件資訊與頁碼" onClose={()=>setInfoOpen(false)}><p className="full-document-name">{p.name}</p><p role="status">{p.status}</p><div className="page-navigation"><IconButton label="上一頁" disabled={!p.ready||p.page<=1} onClick={()=>p.onPage(p.page-1)}><ChevronLeft size={18}/></IconButton><NumberInput label="頁碼" disabled={!p.ready} integer value={p.page} min={1} max={p.pages} onCommit={p.onPage}/><span>/ {p.pages}</span><IconButton label="下一頁" disabled={!p.ready||p.page>=p.pages} onClick={()=>p.onPage(p.page+1)}><ChevronRight size={18}/></IconButton></div></Dialog>}
    {exportOpen&&<Dialog title="匯出文件" onClose={()=>setExportOpen(false)}><p>工作存檔保留可編輯筆記；合併 PDF 適合分享與列印。</p>{p.dirty&&<p className="field-error">尚有草稿；文字會先嘗試保存，未套用屬性保留在面板，不包含於匯出。</p>}<div className="export-actions"><Button onClick={()=>{setExportOpen(false);p.onExport('note');}}>工作存檔</Button><Button onClick={()=>{setExportOpen(false);p.onExport('pdf');}}>匯出 PDF</Button></div></Dialog>}
  </div>;
}

export function ToolOptions(p:Pick<ToolbarProps,'tool'|'color'|'onColor'|'weight'|'onWeight'|'eraserSize'|'onEraser'|'selectionMode'|'onSelectionMode'>){
  const config=toolSettings(p.tool);if(!Object.values(config).some(Boolean))return null;
  return <div className="tool-options" aria-label="目前工具設定">{config.color&&<label>顏色<input aria-label="畫筆顏色" type="color" value={p.color} onChange={e=>p.onColor(e.target.value)}/></label>}{config.weight&&<SizeControl label="直徑" value={p.weight} onChange={p.onWeight}/>} {config.eraser&&<SizeControl label="橡皮擦直徑" value={p.eraserSize} min={2} onChange={p.onEraser}/>} {config.selection&&<div className="selection-tools" role="toolbar" aria-label="選取模式">{([['box','方框'],['lasso','自由選取']] as const).map(([mode,label])=><Button key={mode} aria-pressed={p.selectionMode===mode} className={p.selectionMode===mode?'active':''} onClick={()=>p.onSelectionMode(mode)}>{label}</Button>)}</div>}</div>;
}

export function PageSettings(p:Pick<ToolbarProps,'layout'|'onLayout'|'zoom'|'onZoom'|'ready'|'zoomMode'|'onFit'|'onFitPage'|'onRotate'>){return <div id="page-settings" className="page-settings"><label>展示方向<select aria-label="展示方向" value={p.layout} onChange={e=>p.onLayout(e.target.value as ToolbarProps['layout'])}><option value="vertical">垂直連續</option><option value="horizontal">水平連續</option></select></label><IconButton label="縮小" onClick={()=>p.onZoom(Math.max(.25,p.zoom-.25))}><Minus size={18}/></IconButton><span>{Math.round(p.zoom*100)}%</span><IconButton label="放大" onClick={()=>p.onZoom(Math.min(4,p.zoom+.25))}><Plus size={18}/></IconButton><Button disabled={!p.ready} aria-pressed={p.zoomMode==='width'} onClick={p.onFit}>適合寬度</Button><Button disabled={!p.ready} aria-pressed={p.zoomMode==='page'} onClick={p.onFitPage}>適合整頁</Button><IconButton label="旋轉頁面" disabled={!p.ready} onClick={p.onRotate}><RotateCw size={18}/></IconButton></div>;}
