import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ChevronLeft, ChevronRight, RotateCw, Minus, Plus, MousePointer2, Hand, PenLine, Highlighter, Type, ImagePlus, Eraser, Undo2, Redo2, Download, Search } from 'lucide-react';
import { Button, Dialog, IconButton } from './ui';
import { NumberInput, SizeControl } from './NumericControl';
import { toolSettings } from '../core/ui-policy';
export type Tool='read'|'select'|'pen'|'highlight'|'text'|'erase'|'image';
export type SelectionMode='box'|'lasso';
type Props={name:string;status:string;tool:Tool;onTool:(t:Tool)=>void;color:string;onColor:(s:string)=>void;weight:number;onWeight:(n:number)=>void;eraserSize:number;onEraser:(n:number)=>void;onBack:()=>void;onExport:(k:'pdf'|'note')=>void;onImage:()=>void;ready:boolean;working:boolean;canUndo:boolean;canRedo:boolean;onUndo:()=>void;onRedo:()=>void;selectionMode:SelectionMode;onSelectionMode:(m:SelectionMode)=>void;dirty:boolean;page:number;pages:number;onPage:(n:number)=>void;zoom:number;onZoom:(n:number)=>void;onFit:()=>void;onFitPage:()=>void;zoomMode:'manual'|'width'|'page';onRotate:()=>void;layout:'vertical'|'horizontal';onLayout:(l:'vertical'|'horizontal')=>void;query:string;onQuery:(s:string)=>void;onSearch:()=>void;onPrevious?:()=>void;searchSummary?:string};
export function EditorToolbar(p:Props){
  const [exportOpen,setExportOpen]=useState(false),[searchOpen,setSearchOpen]=useState(false),[settingsOpen,setSettingsOpen]=useState(false);
  const search=useRef<HTMLInputElement>(null),searchToggle=useRef<HTMLButtonElement>(null);
  useEffect(()=>{if(searchOpen)search.current?.focus();},[searchOpen]);
  const config=toolSettings(p.tool);
  const modes:[Tool,typeof Hand,string][]=[['read',Hand,'閱讀'],['select',MousePointer2,'選取'],['pen',PenLine,'畫筆'],['highlight',Highlighter,'螢光筆'],['text',Type,'文字'],['erase',Eraser,'橡皮擦']];
  return <div className="editor-controls">
    <header className="reader-header"><IconButton label="返回文件庫" onClick={p.onBack}><ArrowLeft size={20}/></IconButton><div className="reader-title"><strong>{p.name}</strong><small role="status">{p.status}</small></div><Button aria-label="匯出文件" onClick={()=>setExportOpen(true)}><Download size={18}/><span>匯出</span></Button></header>
    <div className="tools"><div className="tool-group tool-modes" role="toolbar" aria-label="筆記工具（窄版可左右捲動）">{modes.map(([id,Icon,label])=><Button key={id} variant="quiet" className={p.tool===id?'active':''} onClick={()=>p.onTool(id)} aria-label={label} aria-pressed={p.tool===id}><Icon size={19}/><span>{label}</span></Button>)}<IconButton aria-pressed={p.tool==='image'} className={p.tool==='image'?'active':''} label="插入圖片" onClick={p.onImage} disabled={!p.ready}><ImagePlus size={19}/></IconButton></div><div className="tool-group history-tools"><IconButton label="復原" disabled={!p.canUndo||p.working} onClick={p.onUndo}><Undo2 size={19}/></IconButton><IconButton label="重做" disabled={!p.canRedo||p.working} onClick={p.onRedo}><Redo2 size={19}/></IconButton></div></div>
    <div className="tool-options" aria-label="目前工具設定">{config.color&&<label>顏色<input aria-label="畫筆顏色" type="color" value={p.color} onChange={e=>p.onColor(e.target.value)}/></label>}{config.weight&&<SizeControl label="直徑" value={p.weight} onChange={p.onWeight}/>} {config.eraser&&<SizeControl label="橡皮擦直徑" value={p.eraserSize} min={2} onChange={p.onEraser}/>} {config.selection&&<div className="selection-tools" role="toolbar" aria-label="選取模式">{([['box','方框'],['lasso','自由選取']] as const).map(([mode,label])=><Button key={mode} aria-pressed={p.selectionMode===mode} className={p.selectionMode===mode?'active':''} onClick={()=>p.onSelectionMode(mode)}>{label}</Button>)}</div>}</div>
    <div className="page-controls"><div className="page-navigation"><IconButton label="上一頁" disabled={!p.ready||p.page<=1} onClick={()=>p.onPage(p.page-1)}><ChevronLeft size={18}/></IconButton><label><span className="visually-hidden">頁碼</span><NumberInput label="頁碼" disabled={!p.ready} integer value={p.page} min={1} max={p.pages} onCommit={p.onPage}/> / {p.pages}</label><IconButton label="下一頁" disabled={!p.ready||p.page>=p.pages} onClick={()=>p.onPage(p.page+1)}><ChevronRight size={18}/></IconButton></div>

      <div className="page-secondary"><button ref={searchToggle} aria-label="搜尋 PDF" aria-expanded={searchOpen} aria-controls="pdf-search" onClick={()=>{if(searchOpen)p.onQuery('');setSearchOpen(v=>!v);}}><Search size={18}/><span>搜尋</span></button><Button aria-expanded={settingsOpen} aria-controls="page-settings" onClick={()=>setSettingsOpen(v=>!v)}>頁面設定 · {Math.round(p.zoom*100)}%</Button></div>
    </div>
    {settingsOpen&&<div id="page-settings" className="page-settings"><label>展示方向<select aria-label="展示方向" value={p.layout} onChange={e=>p.onLayout(e.target.value as Props['layout'])}><option value="vertical">垂直連續</option><option value="horizontal">水平連續</option></select></label><IconButton label="縮小" onClick={()=>p.onZoom(Math.max(.25,p.zoom-.25))}><Minus size={18}/></IconButton><span>{Math.round(p.zoom*100)}%</span><IconButton label="放大" onClick={()=>p.onZoom(Math.min(4,p.zoom+.25))}><Plus size={18}/></IconButton><Button disabled={!p.ready} aria-pressed={p.zoomMode==='width'} onClick={p.onFit}>適合寬度</Button><Button disabled={!p.ready} aria-pressed={p.zoomMode==='page'} onClick={p.onFitPage}>適合整頁</Button><IconButton label="旋轉頁面" disabled={!p.ready} onClick={p.onRotate}><RotateCw size={18}/></IconButton></div>}
    {searchOpen&&<form id="pdf-search" className="pdf-search" onSubmit={e=>{e.preventDefault();p.onSearch();}} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();setSearchOpen(false);p.onQuery('');searchToggle.current?.focus();}}}><input ref={search} aria-label="搜尋 PDF 文字" placeholder="搜尋文件文字" value={p.query} onChange={e=>p.onQuery(e.target.value)}/><span role="status">{p.searchSummary}</span><Button disabled={!p.query.trim()} onClick={p.onPrevious}>前一筆</Button><Button type="submit" disabled={!p.ready||!p.query.trim()}>下一筆</Button><Button onClick={()=>{setSearchOpen(false);p.onQuery('');searchToggle.current?.focus();}}>關閉搜尋</Button></form>}
    {exportOpen&&<Dialog title="匯出文件" onClose={()=>setExportOpen(false)}><p>工作存檔保留可編輯筆記；合併 PDF 適合分享與列印。</p>{p.dirty&&<p className="field-error">尚有草稿；文字會先嘗試保存，未套用屬性保留在面板，不包含於匯出。</p>}<div className="export-actions"><Button onClick={()=>{setExportOpen(false);p.onExport('note');}}>工作存檔</Button><Button onClick={()=>{setExportOpen(false);p.onExport('pdf');}}>匯出 PDF</Button></div></Dialog>}
  </div>;
}
