import { ancestry, directFolders, scopeDestination } from '../core/library-browser';
import { ActionMenu, Button, Dialog, Field } from './ui';
import { useEffect, useState } from 'react';
import { Folder, FolderPlus, FilePlus2, Pencil, Trash2 } from 'lucide-react';
import { uid, nameOf, type NoteDocument } from '../core/model';
import { cleanFolderName, classification, folderPath, folderTree, folderParent, canMoveFolder, parentKey, folders, folderName, folderKey, libraryEdit, memberKey, type LibraryState } from '../core/library';
import { dragged, startDrag, endDrag, suppressDragClick } from '../core/drag';
import { store } from '../core/storage';
export type LibraryGuard=Parameters<typeof store.saveLibrary>[1];
type Props={browse?:boolean;library:LibraryState;documents:NoteDocument[];scope:string;device:string;query?:string;onQuery?:(value:string)=>void;canBack?:boolean;onBack?:()=>void;onScope:(id:string)=>void;onChange:(state:LibraryState,guard?:LibraryGuard)=>Promise<void>;onCreate:(name:string,orientation:'portrait'|'landscape')=>Promise<void>;move?:NoteDocument;onCloseMove:()=>void;onError:(e:unknown)=>void};
export function LibraryPanel({browse=true,library,documents,scope,device,query='',onQuery,canBack=false,onBack,onScope,onChange,onCreate,move,onCloseMove,onError}:Props){
  const list=folderTree(library),visibleIds=new Set(directFolders(library,scope,query).map(f=>f.id)),path=ancestry(library,scope),visible=list.filter(f=>visibleIds.has(f.id));const [folderForm,setFolderForm]=useState<{id?:string;name:string;parentId?:string|null}>();const [remove,setRemove]=useState<string>();
  const [blank,setBlank]=useState(false),[name,setName]=useState(''),[orientation,setOrientation]=useState<'portrait'|'landscape'>('portrait'),[saving,setSaving]=useState(false);
  const [target,setTarget]=useState('');const [moveFolder,setMoveFolder]=useState<string>();const [dropTarget,setDropTarget]=useState('');const [dragStatus,setDragStatus]=useState('');
  useEffect(()=>{const end=()=>{setDropTarget('');setDragStatus('');};window.addEventListener('pdfnote-drag-end',end);return ()=>window.removeEventListener('pdfnote-drag-end',end);},[]);
  const repeated=new Set(list.filter(f=>list.some(other=>other.id!==f.id&&folderParent(library,other.id).parentId===folderParent(library,f.id).parentId&&other.name.toLocaleLowerCase()===f.name.toLocaleLowerCase())).map(f=>f.id));
  async function task(action:()=>Promise<void>){if(saving)return;setSaving(true);try{await action();}catch(e){onError(e);}finally{setSaving(false);}}
  function dropProps(id:string|null,kind:'folder'|'unfiled'|'root'){
    function valid(){const item=dragged();if(!item)throw new Error('沒有拖曳項目');if(item.kind==='document'){if(id&&folderParent(library,id).issue)throw new Error('目的階層待處理');if(id&&list.find(f=>f.id===id)?.conflicted)throw new Error('目的資料夾有衝突');}else{if(kind==='unfiled')throw new Error('資料夾請移至根層');canMoveFolder(library,item.id,id);}return item;}
    return {onDragOver:(e:React.DragEvent)=>{e.preventDefault();try{valid();e.dataTransfer.dropEffect='move';setDropTarget(kind+':'+id);setDragStatus('放開以移動至 '+(id?folderName(library,id):kind==='root'?'資料夾根層':'未分類'));}catch(err){e.dataTransfer.dropEffect='none';setDropTarget('');setDragStatus((err as Error).message);}},onDragLeave:()=>setDropTarget(''),onDrop:(e:React.DragEvent)=>{e.preventDefault();setDropTarget('');try{const item=valid();const current=item.kind==='folder'?folderParent(library,item.id):classification(library,item.id);const unchanged=item.kind==='folder'?!current.issue&&folderParent(library,item.id).parentId===id:!current.issue&&classification(library,item.id).folderId===id;if(unchanged){setDragStatus('位置相同，未變更');return;}void task(async()=>{await onChange(libraryEdit(library,item.kind==='folder'?parentKey(item.id):memberKey(item.id),item.kind==='folder'?{parentId:id}:{folderId:id},device),{target:id,...(item.kind==='folder'?{moveFolder:item.id}:{})});setDragStatus('移動完成');});}catch(err){setDragStatus((err as Error).message);}finally{endDrag();}}};
  }
  return <section className="library-panel" aria-label="資料夾與新建文件">
    {browse&&<><div className="creation-actions"><button disabled={!device} onClick={()=>setFolderForm({name:'',parentId:scopeDestination(scope)})}><FolderPlus size={17}/>新增資料夾</button><button disabled={!device} onClick={()=>{setName('');setOrientation('portrait');setBlank(true);}}><FilePlus2 size={17}/>新建空白文件</button></div>
    <nav className="folder-breadcrumbs" aria-label="資料夾路徑"><button disabled={!canBack} onClick={onBack}>← 返回</button><button aria-label="前往我的文件根目錄" aria-current={scope==='root'?'page':undefined} data-drop-target="root" className={dropTarget==='root:null'?'drop-active':''} {...dropProps(null,'root')} onClick={()=>{if(!suppressDragClick())onScope('root');}}>我的文件</button>
      {path.length>3&&<ActionMenu label="較上層路徑" caption="較上層路徑…">{path.slice(0,-3).map(id=><button key={id} {...dropProps(id,'folder')} className={dropTarget==='folder:'+id?'drop-active':''} onClick={()=>{if(!suppressDragClick())onScope(id);}}>{folderName(library,id)}</button>)}</ActionMenu>}
      {path.slice(-3).map(id=><span key={id}><span aria-hidden="true"> / </span><button {...dropProps(id,'folder')} className={dropTarget==='folder:'+id?'drop-active':''} aria-current={id===scope?'page':undefined} onClick={()=>{if(!suppressDragClick())onScope(id);}}>{folderName(library,id)}</button></span>)}
      {scope==='all'&&<span aria-current="page"> / 全部文件</span>}{scope==='unfiled'&&<span aria-current="page"> / 未分類</span>}
    </nav>
    <div className="folder-views"><button aria-pressed={scope==='all'} onClick={()=>onScope('all')}>全部文件</button><button {...dropProps(null,'unfiled')} data-drop-target="unfiled" aria-pressed={scope==='unfiled'} onClick={()=>onScope('unfiled')}>未分類</button></div>
    <label className="search-box folder-search"><span className="visually-hidden">搜尋資料夾與文件名稱</span><input placeholder="搜尋資料夾與文件名稱…" aria-label="搜尋資料夾與文件名稱" aria-describedby="search-scope" value={query} onChange={e=>onQuery?.(e.target.value)}/></label>
    <p id="search-scope" className="scope-caption">搜尋範圍：{scope==='all'?'全部資料夾與文件':scope==='root'?'我的文件根目錄（直接子項目）':scope==='unfiled'?'未分類文件':folderPath(library,scope)+'（直接子項目）'}</p><p className="drag-status" role="status">{dragStatus}</p>
    {!!visible.length&&<div className="folder-grid" aria-label="此層資料夾">{visible.map(folder=><div draggable onDragStart={e=>startDrag(e,{kind:'folder',id:folder.id})} onDragEnd={()=>{endDrag();setDropTarget('');setDragStatus('');}} {...dropProps(folder.id,'folder')} data-folder-id={folder.id} className={'folder-tile '+(scope===folder.id?'selected ':'')+(dropTarget==='folder:'+folder.id?'drop-active':'')} key={folder.id}><button aria-pressed={scope===folder.id} className="folder-open" aria-label={'開啟資料夾 '+folder.name} onClick={()=>{if(!suppressDragClick())onScope(folder.id);}}><Folder size={21}/><span><strong>{folder.name}</strong><small className="folder-path">{folderPath(library,folder.id)}</small><small>{documents.filter(d=>classification(library,d.id).folderId===folder.id).length} 份文件{folder.conflicted?' · 名稱有衝突':''}{folder.issue?' · '+folder.issue:''}{repeated.has(folder.id)?' · 同名，請改名 · '+folder.id.slice(0,8):''}</small></span></button><ActionMenu label={'管理資料夾 '+folder.name}><button aria-label={'移動資料夾 '+folder.name} onClick={()=>{setTarget('');setMoveFolder(folder.id);}}>移動</button><button aria-label={'重新命名資料夾 '+folder.name} disabled={folder.conflicted} onClick={()=>setFolderForm({id:folder.id,name:folder.name})}><Pencil size={14}/>重新命名</button><button aria-label={'刪除資料夾 '+folder.name} disabled={folder.conflicted} onClick={()=>setRemove(folder.id)}><Trash2 size={14}/>刪除資料夾</button></ActionMenu></div>)}</div>}
    </>}
    {folderForm&&<Dialog title={folderForm.id?'重新命名資料夾':'新增資料夾'} onClose={()=>setFolderForm(undefined)} dismissible={!saving}><form aria-label={folderForm.id?'重新命名資料夾':'新增資料夾'} onSubmit={e=>{e.preventDefault();void task(async()=>{const cleaned=cleanFolderName(folderForm.name,library,folderForm.id,folderForm.parentId),id=folderForm.id||uid();let next=libraryEdit(library,folderKey(id),{name:cleaned},device);if(!folderForm.id&&folderForm.parentId)next=libraryEdit(next,parentKey(id),{parentId:folderForm.parentId},device);await onChange(next,{name:cleaned,folderId:folderForm.id,parentId:folderForm.parentId,target:folderForm.parentId});setFolderForm(undefined);if(!folderForm.id)onScope(id);});}}><Field label="資料夾名稱"><input maxLength={100} aria-label="資料夾名稱" value={folderForm.name} onChange={e=>setFolderForm({...folderForm,name:e.target.value})}/></Field><div className="modal-actions"><button type="button" disabled={saving} onClick={()=>setFolderForm(undefined)}>取消</button><button className="primary" disabled={saving}>{saving?'儲存中…':'儲存資料夾'}</button></div></form></Dialog>}
    {remove&&<Dialog title={`刪除資料夾「${folderName(library,remove)}」？`} onClose={()=>setRemove(undefined)} dismissible={!saving}><p>只允許刪除空資料夾，不會連帶刪除任何文件。已刪除的文件也需先移出。</p><div className="modal-actions"><button disabled={saving} onClick={()=>setRemove(undefined)}>取消</button><button className="danger" disabled={saving} onClick={()=>void task(async()=>{await onChange(libraryEdit(library,folderKey(remove),null,device),{emptyFolder:remove});setRemove(undefined);})}>確認刪除資料夾</button></div></Dialog>}
    {(move||moveFolder)&&<Dialog title={`移動「${move?nameOf(move):folderName(library,moveFolder!)}」`} onClose={()=>{onCloseMove();setMoveFolder(undefined);setTarget('');}} dismissible={!saving}><form onSubmit={e=>{e.preventDefault();void task(async()=>{if(moveFolder){canMoveFolder(library,moveFolder,target||null);if(folderParent(library,moveFolder).issue||folderParent(library,moveFolder).parentId!==(target||null))await onChange(libraryEdit(library,parentKey(moveFolder),{parentId:target||null},device,true),{target:target||null,moveFolder});}else if(move&&(classification(library,move.id).issue||classification(library,move.id).folderId!==(target||null)))await onChange(libraryEdit(library,memberKey(move.id),{folderId:target||null},device),{target:target||null});onCloseMove();setMoveFolder(undefined);setTarget('');});}}><p>只變更分類，不複製 PDF 或更換文件 ID。目的地預設為未分類，確認後才會移動。</p><label>目的資料夾<select aria-label="目的資料夾" value={target} onChange={e=>setTarget(e.target.value)}><option value="">{moveFolder?'資料夾根層':'未分類'}</option>{list.filter(f=>{if(f.conflicted||f.issue)return false;if(moveFolder){try{canMoveFolder(library,moveFolder,f.id);}catch{return false;}}return true;}).map(f=><option value={f.id} key={f.id}>{folderPath(library,f.id)}</option>)}</select></label><div className="modal-actions"><button type="button" disabled={saving} onClick={()=>{onCloseMove();setMoveFolder(undefined);setTarget('');}}>取消</button><button className="primary" disabled={saving}>確認移動</button></div></form></Dialog>}
    {blank&&<Dialog title="新建空白文件" onClose={()=>setBlank(false)} dismissible={!saving}><form aria-label="建立空白文件" onSubmit={e=>{e.preventDefault();void task(async()=>{await onCreate(name,orientation);setBlank(false);});}}><Field label="文件名稱"><input aria-label="空白文件名稱" maxLength={200} placeholder="留空會自動命名" value={name} onChange={e=>setName(e.target.value)}/></Field><fieldset className="orientation-options"><legend>A4 · 白底 · 一頁</legend>{(['portrait','landscape'] as const).map(o=><label key={o} className={orientation===o?'chosen':''}><input type="radio" name="orientation" value={o} checked={orientation===o} onChange={()=>setOrientation(o)}/><span className={'orientation-paper '+o}/><span>{o==='portrait'?'直式':'橫式'}</span></label>)}</fieldset><p className="muted small">儲存至：{scopeDestination(scope)===null?'我的文件根目錄／未分類':folderPath(library,scope)}。建立後保持固定版面，直接開始寫筆記。</p><div className="modal-actions"><button type="button" disabled={saving} onClick={()=>setBlank(false)}>取消</button><button className="primary" disabled={saving}>{saving?'建立中…':'建立文件'}</button></div></form></Dialog>}
  </section>;
}
