import { Button, StatusBadge } from './ui';
import { useState } from 'react';
import { nameOf, type NoteDocument } from '../core/model';
import { hierarchyIssues, folderName, libraryConflicts, type LibraryOperation, type LibraryState } from '../core/library';
export function LibraryConflicts({library,documents,onResolve,onRoot}:{library:LibraryState;documents:NoteDocument[];onRoot:(id:string)=>Promise<void>;onResolve:(entity:string,version:LibraryOperation)=>Promise<void>}){
  const list=libraryConflicts(library),[selected,setSelected]=useState<string>(),[saving,setSaving]=useState(false),[error,setError]=useState('');
  const issues=hierarchyIssues(library);if(!list.length&&!issues.length)return null;
  return <section className="management-conflicts"><h2>分類管理衝突</h2><p>這些版本影響資料夾名稱或文件歸屬；全部文件仍可閱讀及註記。</p>{issues.map(f=><article className="management-conflict" key={f.id}><h3>{f.name} · {f.issue}</h3><button disabled={saving} onClick={async()=>{setSaving(true);try{await onRoot(f.id);}catch(e){setError(String(e));}finally{setSaving(false);}}}>將此資料夾移回根層</button></article>)}{list.map(item=><article className="management-conflict" key={item.entity}><h3>{item.entity.startsWith('folder:')?'資料夾名稱／刪除 · '+item.entity.slice(7,15):item.entity.startsWith('parent:')?'資料夾父層 · '+folderName(library,item.entity.slice(7)):'文件歸屬 · '+(documents.find(d=>d.id===item.entity.slice(7))?nameOf(documents.find(d=>d.id===item.entity.slice(7))!):'文件尚未下載')}</h3><div className="version-tabs">{item.versions.map((v,i)=><button disabled={saving} aria-pressed={selected===v.id} key={v.id} className={selected===v.id?'active':''} onClick={()=>setSelected(v.id)}>分類版本 {i+1}：{v.value===null?'已刪除':('name' in v.value?v.value.name:'parentId' in v.value?(v.value.parentId?folderName(library,v.value.parentId):'資料夾根層'):folderName(library,v.value.folderId))}</button>)}</div>{item.versions.filter(v=>v.id===selected).map(v=><div key={v.id}><p className="version-info">裝置 {v.device.slice(0,8)} · {new Date(v.time).toLocaleString('zh-TW')}</p><button disabled={saving} className="primary" onClick={async()=>{setSaving(true);setError('');try{await onResolve(item.entity,v);setSelected(undefined);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setSaving(false);}}}>保留此分類版本</button></div>)}</article>)}{saving&&<p role="status">正在保存選擇…</p>}{error&&<p className="field-error" role="alert">{error}</p>}</section>;
}
